name: build
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build the ansible execution environment
        run: ./ansible-lint.sh --version
      - name: Lint the example.yml playbook
        run: ./ansible-lint.sh --offline --parseable example.yml
      - name: Lint the example-destroy.yml playbook
        run: ./ansible-lint.sh --offline --parseable example-destroy.yml
